### PR TITLE
Add Sublime Text Color Scheme

### PR DESCRIPTION
**Pull request by driesvints**
After some trial and error, I managed to set up a working build for a Sublime Text color scheme 😄 

The color scheme isn't perfect yet and probably needs some tweaking as well as adding more tags which should be colored. [Feel free to help out on improving it!](https://github.com/driesvints/nova-sublime-text)

I eventually also want to add a `Nove.sublime-theme` file for the UI of Sublime Text as well as put it up on Package control.

Btw, I don't really know how to add and icon for Sublime Text. Am I correct to guess that you have a paid pack for IcoMoon which contains the icon? If so: can you add an icon for Sublime Text to master so I can rebase? Perhaps also add one for PHPStorm as well because I'm planning to send a PR for that as well :)

Thanks and let me know what you think!

### CODE REVIEW

**Comment by trevordmiller** [comment]
@driesvints Does that feedback make sense?

**Comment by driesvints** [comment]
@trevordmiller yes it does! Sorry, haven't had time yet to process the feedback. Not sure when I'll have this week. But if I can push an update I'll let you know.

**Comment by trevordmiller** [comment]
@driesvints No worries :) Will look forward to it.

**Comment by driesvints** [comment]
@trevordmiller I updated the screenshot. Is that better? 

I can't add the icon because the library you suggested doesn't has an icon for Sublime Text. Is there any alternative we can use?

Tbh, I could really use help from someone who can check if I have the correct colors in place: https://github.com/driesvints/nova-sublime-text/blob/master/src/index.js
Perhaps there are more tags/types which I can/should add?

**Comment by trevordmiller** [comment]
@driesvints Yes the screenshot looks much better! I can take care of the icon once you are ready to merge. As for the syntax groups, I don't use Sublime so I don't know. I would recommend researching other themes and a full list of available syntax groups and make sure you are at least supporting those for JavaScript, HTML, and CSS using the `nova-colors.syntaxGroups` mappings. Make sense? Let me know when you are ready to merge and I'll add the icon to the site. Thanks!

**Comment by trevordmiller** [comment]
@driesvints Did you see my last comment? Am still very interested in merging this after you get the code updated; I can handle adding the icon and updating the website once you are ready with the plugin.

**Comment by trevordmiller** [comment]
Posted this in the sublime issue: "I'm closing this for now, since it is lower priority than other things I'm working on. I know some attempts have been made to create a sublime plugin; I appreciate it! However, none of these have been complete or used the `nova-colors` package as the other official plugins do and I don't plan to support this myself. If anyone would like to re-open the issue and submit a pull request, let me know! I'd be happy to have your contribution :)"

**Comment by driesvints** [comment]
@trevordmiller if you want you can merge this and add an icon. This is fine for a first release. Once the theme has been released and gains some traction more people probably want to contribute and improve it by sending PR's. At least this way there will be an official ST version of the theme to which users can contribute. 

I have a PR open on package control to make it more easily installable in ST: https://github.com/wbond/package_control_channel/pull/5937
Hope it gets merged soon.

**Comment by trevordmiller** [comment]
@driesvints Please see last comment: "As for the syntax groups, I don't use Sublime so I don't know. I would recommend researching other themes and a full list of available syntax groups and make sure you are at least supporting those for JavaScript, HTML, and CSS using the nova-colors.syntaxGroups mappings. Make sense? Let me know when you are ready to merge and I'll add the icon to the site. Thanks!"
I don't feel comfortable merging this until it is using `nova-colors` fully. But if you can update it I'd gladly merge it in and add it to the website :)

**Comment by driesvints** [comment]
@trevordmiller ok, no worries. I'll try to reach out to see if anyone can help out.

**Pull request closed without merging**
