### PR TITLE
Error tracking

### PR DESCRIPTION
**Pull request by colindevs**
Added error tracking with Sentry.

### CODE REVIEW

**Comment by colindevs** [comment]
Got it, just updated the file online.

**Comment by colindevs** [comment]
No, thank you for the opportunity to contribute!

**Comment by trevordmiller** [comment]
cc: @iammerrick

**Comment by trevordmiller** [comment]
@colindevs Looks like it's working ;)

screen shot 2016-10-08 at 3 54 50 pm
screen shot 2016-10-08 at 3 54 37 pm

**Comment by colindevs** [comment]
Great! Thank you for letting me do it.

**Pull request merged**
